// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	proto/auth/auth.proto

It has these top-level messages:
	User
	Request
	Response
	Token
	Error
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Company  string `protobuf:"bytes,4,opt,name=company" json:"company,omitempty"`
	Password string `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Request struct {
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Response struct {
	User   *User    `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Users  []*User  `protobuf:"bytes,2,rep,name=users" json:"users,omitempty"`
	Errors []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Token struct {
	Token  string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Valid  bool     `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
	Errors []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code        int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*Token)(nil), "Token")
	proto.RegisterType((*Error)(nil), "Error")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Auth service

type AuthClient interface {
	Create(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	Get(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	GetAll(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Auth(ctx context.Context, in *User, opts ...client.CallOption) (*Token, error)
	ValidateToken(ctx context.Context, in *Token, opts ...client.CallOption) (*Token, error)
}

type authClient struct {
	c           client.Client
	serviceName string
}

func NewAuthClient(serviceName string, c client.Client) AuthClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "auth"
	}
	return &authClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *authClient) Create(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Get(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.Get", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetAll(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.GetAll", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Auth(ctx context.Context, in *User, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.Auth", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ValidateToken(ctx context.Context, in *Token, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.ValidateToken", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthHandler interface {
	Create(context.Context, *User, *Response) error
	Get(context.Context, *User, *Response) error
	GetAll(context.Context, *Request, *Response) error
	Auth(context.Context, *User, *Token) error
	ValidateToken(context.Context, *Token, *Token) error
}

func RegisterAuthHandler(s server.Server, hdlr AuthHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Auth{hdlr}, opts...))
}

type Auth struct {
	AuthHandler
}

func (h *Auth) Create(ctx context.Context, in *User, out *Response) error {
	return h.AuthHandler.Create(ctx, in, out)
}

func (h *Auth) Get(ctx context.Context, in *User, out *Response) error {
	return h.AuthHandler.Get(ctx, in, out)
}

func (h *Auth) GetAll(ctx context.Context, in *Request, out *Response) error {
	return h.AuthHandler.GetAll(ctx, in, out)
}

func (h *Auth) Auth(ctx context.Context, in *User, out *Token) error {
	return h.AuthHandler.Auth(ctx, in, out)
}

func (h *Auth) ValidateToken(ctx context.Context, in *Token, out *Token) error {
	return h.AuthHandler.ValidateToken(ctx, in, out)
}

func init() { proto.RegisterFile("proto/auth/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x4f, 0xe3, 0x30,
	0x10, 0xc5, 0xdb, 0xfc, 0x6b, 0x3a, 0xd5, 0xee, 0x61, 0xb4, 0xab, 0x75, 0xbb, 0x08, 0x4a, 0x4e,
	0x9c, 0x82, 0x54, 0xce, 0x1c, 0x2a, 0x84, 0x7a, 0x0f, 0x7f, 0xee, 0x6e, 0x33, 0x52, 0x23, 0xd2,
	0x38, 0xd8, 0x4e, 0x11, 0xdf, 0x85, 0x0f, 0x8b, 0x3c, 0x71, 0x29, 0x48, 0x48, 0x5c, 0x92, 0x79,
	0xbf, 0xe7, 0x38, 0x7e, 0x4f, 0x86, 0xbf, 0xad, 0x56, 0x56, 0x5d, 0xca, 0xce, 0x6e, 0xf9, 0x91,
	0xb3, 0xce, 0xf6, 0x10, 0x3d, 0x18, 0xd2, 0xf8, 0x1b, 0x82, 0xaa, 0x14, 0xc3, 0xf9, 0xf0, 0x62,
	0x5c, 0x04, 0x55, 0x89, 0x08, 0x51, 0x23, 0x77, 0x24, 0x02, 0x26, 0x3c, 0xe3, 0x1f, 0x88, 0x69,
	0x27, 0xab, 0x5a, 0x84, 0x0c, 0x7b, 0x81, 0x02, 0x46, 0x1b, 0xb5, 0x6b, 0x65, 0xf3, 0x2a, 0x22,
	0xe6, 0x07, 0x89, 0x33, 0x48, 0x5b, 0x69, 0xcc, 0x8b, 0xd2, 0xa5, 0x88, 0xd9, 0xfa, 0xd0, 0xd9,
	0x18, 0x46, 0x05, 0x3d, 0x77, 0x64, 0x6c, 0xb6, 0x86, 0xb4, 0x20, 0xd3, 0xaa, 0xc6, 0x10, 0x4e,
	0x21, 0xea, 0x0c, 0x69, 0x3e, 0xc8, 0x64, 0x11, 0xe7, 0xee, 0x6c, 0x05, 0x23, 0xfc, 0x0f, 0xb1,
	0x7b, 0x1b, 0x11, 0xcc, 0xc3, 0xa3, 0xd7, 0x33, 0x3c, 0x85, 0x84, 0xb4, 0x56, 0xda, 0x88, 0x90,
	0xdd, 0x24, 0xbf, 0x75, 0xb2, 0xf0, 0x34, 0xbb, 0x83, 0xf8, 0x5e, 0x3d, 0x51, 0xe3, 0x32, 0x58,
	0x37, 0xf8, 0xa8, 0xbd, 0x70, 0x74, 0x2f, 0xeb, 0xaa, 0xe4, 0xb8, 0x69, 0xd1, 0x8b, 0x1f, 0x37,
	0xbd, 0x86, 0x98, 0x81, 0x2b, 0x6b, 0xa3, 0x4a, 0xe2, 0x3d, 0xe3, 0x82, 0x67, 0x9c, 0xc3, 0xa4,
	0x24, 0xb3, 0xd1, 0x55, 0x6b, 0x2b, 0xd5, 0xf8, 0x1e, 0x3f, 0xa3, 0xc5, 0xdb, 0x10, 0xa2, 0x65,
	0x67, 0xb7, 0x78, 0x02, 0xc9, 0x8d, 0x26, 0x69, 0x09, 0xfb, 0x50, 0xb3, 0x71, 0x7e, 0x28, 0x24,
	0x1b, 0xe0, 0x14, 0xc2, 0x15, 0xd9, 0x6f, 0xad, 0x33, 0x48, 0x56, 0x64, 0x97, 0x75, 0x8d, 0x69,
	0xee, 0xdb, 0xfc, 0xba, 0xe0, 0x9f, 0xff, 0x83, 0xff, 0x38, 0xc9, 0xb9, 0x84, 0x6c, 0x80, 0xe7,
	0xf0, 0xeb, 0xd1, 0x65, 0x94, 0x96, 0xfa, 0x5e, 0xbc, 0x75, 0x5c, 0xb2, 0x4e, 0xf8, 0x82, 0x5c,
	0xbd, 0x07, 0x00, 0x00, 0xff, 0xff, 0x30, 0x1c, 0x78, 0xf7, 0x39, 0x02, 0x00, 0x00,
}
